version: 0.0
Resources:
  - HelloWorldFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "my-first-stack-HelloWorldFunction-OOK4Q46L4UXY"
        CurrentVersion: "1"
        TargetVersion: "2"
Hooks:
  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"
