version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
      - node bin/app.js

artifacts:
  files:
    - bin/app.js

